### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by LuckyHH** [LuckyHH/WebSplider#1]
使用发现有什么问题的，请在这里反馈哦

**Comment by JZLeung** [comment]
配置：
目标网页： https://www.doulook.com/category/redian/


```json
{ "state": false, "time": "2018-08-14T17:09:20.045Z", "data": "Error: Error: Moved Permanently" }
```

**Comment by LuckyHH** [comment]
不好意思，原来的解释有错误。我单独使用superagent进行请求该网址，可以请求成功。目前正在查找问题中。

**Comment by LuckyHH** [comment]
Bug已修复。

**Comment by LuckyHH** [comment]
出现这个错误一般是找不到后台接口导致的。。刚才在升级HTTP到HTTPS，所以关闭了Nginx一会。。现在你再试试就好了。。还有就是推荐使用部署在Heroku上的WebSplider，因为我的服务器老捣鼓一些东西，可能并不是非常的稳定。。

**Comment by JZLeung** [comment]
@LuckyHH 
好。谢谢。

**Comment by JZLeung** [comment]
https://websplider.herokuapp.com/user

老哥，我又来麻烦你了。。。。

**Comment by LuckyHH** [comment]
@JZLeung 
这个我也搞不懂为什么。。同样的程序在我服务器上就可以，在Heroku就出现这个错误。。

然后就是用https://splider.herokuapp.com这个新地址吧，这个是前后端分离后的前端面板部分，websplider.heroku.com提供后端API。这里把所有页面集成到一起了。。登录之后点击右上角的“管理页面”就好了。。
